apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world-with-health-checks
  name: hello-world-with-heath-checks
spec:
  containers:
  - image: alexlopezhernandez/docker-exercices:latest
    name: hello-world
    ports:
    - containerPort: 80
      name: http
    resources: {}
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
