apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world-with-resources
  name: hello-world-with-resources
spec:
  containers:
  - image: alexlopezhernandez/docker-exercices:latest
    name: hello-world
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
